### ISSUE TITLE
Wrong version deposited in a link file

### ISSUE THREAD

**Issue by benson-basis** [veithen/alta#2] opened 2016-07-27 17:30 UTC
I've got a case where the link file comes up with:

     ✗ cat target/links/com.fasterxml.jackson.core.jackson-annotations.link
    file:/Users/benson/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.7.0/jackson-annotations-2.7.0.jar

Even though the maven dependency is to 2.7.3. Any ideas?

**Comment by veithen** [comment] 2016-07-27 18:42
Can you share your `pom.xml` file?

**Comment by benson-basis** [comment] 2016-07-27 19:06
Yea, but it won't tell you very much, since it's all tangled up with our
internals.

<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>rosette-osgi-api-impl</artifactId>
    <name>rosette-osgi-api-impl</name>
    <version>4.1.2-SNAPSHOT</version>
    <parent>
        <artifactId>rosette-osgi</artifactId>
        <groupId>com.basistech.osgi</groupId>
        <version>4.1.2-SNAPSHOT</version>
    </parent>
    <description>
      implementation of classes used by the API and common utils.
    </description>
    <dependencies>
      <dependency>
        <groupId>${project.groupId}</groupId>
        <artifactId>rosette-osgi-api</artifactId>
        <version>${project.version}</version>
      </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>16.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.basistech</groupId>
            <artifactId>pax-exam-test-composite</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.inject</groupId>
            <artifactId>javax.inject</artifactId>
            <version>1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <version>1.9</version>
        </dependency>
        
        <dependency>
            <groupId>org.rauschig</groupId>
            <artifactId>jarchivelib</artifactId>
            <version>0.9.100-basis</version>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.core</artifactId>
            <version>6.0.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.basistech</groupId>
            <artifactId>adm-json</artifactId>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>rosette-osgi-test-support</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.jimfs</groupId>
            <artifactId>jimfs</artifactId>
            <version>1.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            
            <plugin>
                <groupId>com.github.veithen.alta</groupId>
                <artifactId>alta-maven-plugin</artifactId>
                <version>0.4</version>
                <executions>
                    <execution>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>generate-files</goal>
                        </goals>
                        <configuration>
                            <separator>-</separator>
                            <name>%groupId%.%artifactId%.%version%.link</name>
                            <value>%url%</value>
                            <dependencySet>
                                <scope>compile</scope>
                            </dependencySet>
                            <artifacts>
                                
                                <artifactItem>
                                    <groupId>com.google.guava</groupId>
                                    <artifactId>guava</artifactId>
                                    <version>18.0</version>
                                </artifactItem>
                            </artifacts>

<outputDirectory>${project.build.directory}/links</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>biz.aQute.bnd</groupId>
                <artifactId>bnd-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>

<manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by veithen** [comment] 2016-07-27 21:52
OK, but I need something to reproduce the problem. Can you create a minimal test project that shows the problem?

**Comment by veithen** [comment] 2016-08-07 20:17
Closing this issue because there is not enough information to reproduce the issue.

**Comment by benson-basis** [comment] 2016-08-07 20:49
Fair enough. I failed to come up with a repro for you.

**Comment by benson-basis** [comment] 2016-09-14 21:12
https://github.com/benson-basis/alta-version-tc is a test case.

run mvn pre-integration-test, and note that the version of jackson-core that ends up in the link is 2.6.x, while the version from dependency:list (and the actual working classpath) is 2.7.3.

**Closed** 2016-09-18 16:36 UTC

**Comment by benson-basis** [comment] 2016-09-18 17:05
Thank You! I would be very grateful for a release.

**Comment by veithen** [comment] 2016-09-18 18:43
Version 0.4.1 is now available.

Thanks for providing a test project!

**Comment by benson-basis** [comment] 2016-09-18 18:45
You're welcome.
